# Generated by ./update.sh - do not update manually!
# Last updated: 2025-12-07
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
    version = "2.1.0";
    src = fetchzip {
      url = "https://d32ifkf9k9ezcg.cloudfront.net/production/sparkle/tuple-2.1.0-2025-12-04-c16a16868.zip";
      hash = "sha256-1mFnMxN5Xd8WGXWa+a7ATOEVj8xpFqSHGUhbKD8pDHw=";
    };
  };
  x86_64-darwin = {
    version = "2.1.0";
    src = fetchzip {
      url = "https://d32ifkf9k9ezcg.cloudfront.net/production/sparkle/tuple-2.1.0-2025-12-04-c16a16868.zip";
      hash = "sha256-1mFnMxN5Xd8WGXWa+a7ATOEVj8xpFqSHGUhbKD8pDHw=";
    };
  };
  aarch64-linux = {
    version = "2025-09-03";
    src = fetchurl {
      url = "https://github.com/tupleapp/linux-release/releases/download/v2025_09_03/tuple-arm64";
      hash = "sha256-67mV5+5Cfsiu07ubTGoLkEcHnQeQBX1bqwC3BLDtDR8=";
    };
  };
  x86_64-linux = {
    version = "2025-09-03";
    src = fetchurl {
      url = "https://github.com/tupleapp/linux-release/releases/download/v2025_09_03/tuple-x64";
      hash = "sha256-Z4VcT8KumpSPx1pM0sXb5QD/cXj9A5rFAk32nWAt9hA=";
    };
  };
}
