# Generated by ./update.sh - do not update manually!
# Last updated: 2026-04-03
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
    version = "2.4.1";
    src = fetchzip {
      url = "https://d32ifkf9k9ezcg.cloudfront.net/production/sparkle/tuple-2.4.1-2026-03-24-530848911.zip";
      hash = "sha256-gC3uVQCQB5zn7TCIS45KJyhy130N7ns9ae1EOyH43Sc=";
    };
  };
  x86_64-darwin = {
    version = "2.4.1";
    src = fetchzip {
      url = "https://d32ifkf9k9ezcg.cloudfront.net/production/sparkle/tuple-2.4.1-2026-03-24-530848911.zip";
      hash = "sha256-gC3uVQCQB5zn7TCIS45KJyhy130N7ns9ae1EOyH43Sc=";
    };
  };
  aarch64-linux = {
    version = "2026-04-02.0";
    src = fetchurl {
      url = "https://tuple-client-releases.s3.amazonaws.com/linux/v2026_04_02.0/arm64/tuple";
      hash = "sha256-TJ5So2deiVQ0L1GNe5Fv3U3b2JenGKNURRrc6jzMDvc=";
    };
  };
  x86_64-linux = {
    version = "2026-04-02.0";
    src = fetchurl {
      url = "https://tuple-client-releases.s3.amazonaws.com/linux/v2026_04_02.0/x86_64/tuple";
      hash = "sha256-Jf1Gg3tFKqB3IhAEcDXNDOlBo52ictl9z2eooiz/7Ec=";
    };
  };
}
