# Generated by ./update.sh - do not update manually!
# Last updated: 2026-04-18
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
    version = "2.4.2";
    src = fetchzip {
      url = "https://d32ifkf9k9ezcg.cloudfront.net/production/sparkle/tuple-2.4.2-2026-04-16-393ded640.zip";
      hash = "sha256-Y72bDkylNfzF1uWoEc8MXlXExmMN8v45loiCEOrmb3M=";
    };
  };
  x86_64-darwin = {
    version = "2.4.2";
    src = fetchzip {
      url = "https://d32ifkf9k9ezcg.cloudfront.net/production/sparkle/tuple-2.4.2-2026-04-16-393ded640.zip";
      hash = "sha256-Y72bDkylNfzF1uWoEc8MXlXExmMN8v45loiCEOrmb3M=";
    };
  };
  aarch64-linux = {
    version = "2026-04-17.0";
    src = fetchurl {
      url = "https://tuple-client-releases.s3.amazonaws.com/linux/v2026_04_17.0/arm64/tuple";
      hash = "sha256-vrpeEbFRA60Bq2kTiH+VJ28IqeuKoGybDi7js2UUbhQ=";
    };
  };
  x86_64-linux = {
    version = "2026-04-17.0";
    src = fetchurl {
      url = "https://tuple-client-releases.s3.amazonaws.com/linux/v2026_04_17.0/x86_64/tuple";
      hash = "sha256-qgxbahTSONynVMCm7X4rzpU8M9q1ZcOeMymc4pM8sLg=";
    };
  };
}
