#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure -p cacert curl jq nix
# shellcheck shell=bash

set -euo pipefail

cd "$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")"

# We assume the 1st redirection is always https://tuple.app/download/mac -> https://production.tuple.app/downloads/latest
# to read the location header of the 2nd one and avoid downloading the archive.
# Another other option would be to follow the redirections all the way (which
# would download the archive) and output %{url_effective}.
DARWIN_URL="$(
  curl \
    --fail \
    --silent \
    --show-error \
    --output=/dev/null \
    --write-out='%header{location}' \
    https://production.tuple.app/downloads/latest
)"

DARWIN_VERSION_RE='/tuple-([0-9]+\.[0-9]+\.[0-9]+)-.+\.zip$'
if [[ "${DARWIN_URL}" =~ ${DARWIN_VERSION_RE} ]]; then
  DARWIN_VERSION="${BASH_REMATCH[1]}"
else
  printf 'Failed to extract darwin version from URL %s with regex %s\n' "${DARWIN_URL}" "${DARWIN_VERSION_RE}" >&2
  exit 1
fi

LINUX_DATA=$(
  curl -L \
    --fail-with-body \
    --silent \
    --show-error \
    --header "Accept: application/vnd.github+json" \
    --header "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/repos/tupleapp/linux-release/releases/latest
)

LINUX_VERSION="$(jq --raw-output '.tag_name | ltrimstr("v") | gsub("_"; "-")' <<<"${LINUX_DATA}")"

AARCH64_LINUX_URL="$(jq --raw-output '.assets[] | select(.name == "tuple-arm64") | .browser_download_url' <<<"${LINUX_DATA}")"
X86_64_LINUX_URL="$(jq --raw-output '.assets[] | select(.name == "tuple-x64") | .browser_download_url' <<<"${LINUX_DATA}")"

darwin_hash=$(nix-prefetch-url --unpack "${DARWIN_URL}")
aarch64_linux_hash=$(nix-prefetch-url "${AARCH64_LINUX_URL}")
x86_64_linux_hash=$(nix-prefetch-url "${X86_64_LINUX_URL}")

# use friendlier hashes

darwin_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "${darwin_hash}")
aarch64_linux_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "${aarch64_linux_hash}")
x86_64_linux_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "${x86_64_linux_hash}")

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
    version = "${DARWIN_VERSION}";
    src = fetchzip {
      url = "${DARWIN_URL}";
      hash = "${darwin_hash}";
    };
  };
  x86_64-darwin = {
    version = "${DARWIN_VERSION}";
    src = fetchzip {
      url = "${DARWIN_URL}";
      hash = "${darwin_hash}";
    };
  };
  aarch64-linux = {
    version = "${LINUX_VERSION}";
    src = fetchurl {
      url = "${AARCH64_LINUX_URL}";
      hash = "${aarch64_linux_hash}";
    };
  };
  x86_64-linux = {
    version = "${LINUX_VERSION}";
    src = fetchurl {
      url = "$X86_64_LINUX_URL";
      hash = "${x86_64_linux_hash}";
    };
  };
}
EOF
