#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure -p cacert curl jq nix xq-xml
# shellcheck shell=bash

set -euo pipefail

cd "$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")"

# Ensure pager is unset for xq
unset PAGER

DARWIN_DATA="$(
  curl \
    --fail-with-body \
    --silent \
    --show-error \
    https://d32ifkf9k9ezcg.cloudfront.net/production/sparkle/appcast.xml
)"

LINUX_DATA="$(
  curl \
    --fail-with-body \
    --silent \
    --show-error \
    --header='Accept: application/vnd.github+json' \
    --header='X-GitHub-Api-Version: 2022-11-28' \
    https://api.github.com/repos/tupleapp/linux-release/releases/latest
)"

DARWIN_VERSION="$(xq --xpath '//rss/channel/item[1]/sparkle:shortVersionString' <<<"${DARWIN_DATA}")"
LINUX_VERSION="$(jq --raw-output '.tag_name | ltrimstr("v") | gsub("_"; "-")' <<<"${LINUX_DATA}")"

DARWIN_URL="$(xq --xpath '//rss/channel/item[1]/enclosure/@url' <<<"${DARWIN_DATA}")"
AARCH64_LINUX_URL="$(jq --raw-output '.assets[] | select(.name == "tuple-arm64") | .browser_download_url' <<<"${LINUX_DATA}")"
X86_64_LINUX_URL="$(jq --raw-output '.assets[] | select(.name == "tuple-x64") | .browser_download_url' <<<"${LINUX_DATA}")"

darwin_hash=$(nix-prefetch-url --unpack "${DARWIN_URL}")
aarch64_linux_hash=$(nix-prefetch-url "${AARCH64_LINUX_URL}")
x86_64_linux_hash=$(nix-prefetch-url "${X86_64_LINUX_URL}")

# use friendlier hashes

darwin_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "${darwin_hash}")
aarch64_linux_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "${aarch64_linux_hash}")
x86_64_linux_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "${x86_64_linux_hash}")

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{ fetchurl, fetchzip }:
{
  aarch64-darwin = {
    version = "${DARWIN_VERSION}";
    src = fetchzip {
      url = "${DARWIN_URL}";
      hash = "${darwin_hash}";
    };
  };
  x86_64-darwin = {
    version = "${DARWIN_VERSION}";
    src = fetchzip {
      url = "${DARWIN_URL}";
      hash = "${darwin_hash}";
    };
  };
  aarch64-linux = {
    version = "${LINUX_VERSION}";
    src = fetchurl {
      url = "${AARCH64_LINUX_URL}";
      hash = "${aarch64_linux_hash}";
    };
  };
  x86_64-linux = {
    version = "${LINUX_VERSION}";
    src = fetchurl {
      url = "$X86_64_LINUX_URL";
      hash = "${x86_64_linux_hash}";
    };
  };
}
EOF
