# Generated by ./update.sh - do not update manually!
# Last updated: 2026-04-18
{ fetchFromGitHub }:
{
  "LuaSnip" = {
    version = "v2.5.0";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "v2.5.0";
      hash = "sha256-diZO1on0rlSp6XuNGN2lNa85rhkNe1QQOejJD+LKkZk=";
    };
  };
  "aerial.nvim" = {
    version = "v3.1.0";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "aerial.nvim";
      rev = "v3.1.0";
      hash = "sha256-ugzNA/+Z2ReIy/8ks9wHEtmpTwpr8qqVR0xemw+GrUc=";
    };
  };
  "astrocore" = {
    version = "v3.0.2";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "astrocore";
      rev = "v3.0.2";
      hash = "sha256-4yf49at22utcEVrLftI8X0iBrcbfVqlZpreXkM0q63E=";
    };
  };
  "astrolsp" = {
    version = "v4.0.0";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "astrolsp";
      rev = "v4.0.0";
      hash = "sha256-N8uwx9PpGey0itrvq/OKOEwtRxXfto0MQ5Tbb7Bnc8w=";
    };
  };
  "astrotheme" = {
    version = "v4.10.1";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "astrotheme";
      rev = "v4.10.1";
      hash = "sha256-rh/cbZcGhpdaprhEs9Cgi2YYNT3B+L+djwFpCn44qeI=";
    };
  };
  "astroui" = {
    version = "v4.0.0";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "astroui";
      rev = "v4.0.0";
      hash = "sha256-290PxuIz8Pc1UWz6Huy0ZQH1CxGeoqN5x2U+VDCRBJc=";
    };
  };
  "better-escape.nvim" = {
    version = "v2.3.3";
    src = fetchFromGitHub {
      owner = "max397574";
      repo = "better-escape.nvim";
      rev = "v2.3.3";
      hash = "sha256-47j0FKQ74HXYHWuKgAlDioGFdYk/XxGU9Qswdd4Rnxw=";
    };
  };
  "blink.cmp" = {
    version = "v1.10.2";
    src = fetchFromGitHub {
      owner = "saghen";
      repo = "blink.cmp";
      rev = "v1.10.2";
      hash = "sha256-C1FpyGw0f35NdHvDUGPXxmKdOgw3SpIteK1gAjVy6Ns=";
    };
  };
  "blink.compat" = {
    version = "v2.5.0";
    src = fetchFromGitHub {
      owner = "saghen";
      repo = "blink.compat";
      rev = "v2.5.0";
      hash = "sha256-GluPgQ8EPH9XXsyLnw//sh1lcDEdcu3VbYQG4ns5JAE=";
    };
  };
  "cmp-dap" = {
    version = "ea92773";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "cmp-dap";
      rev = "ea92773e84c0ad3288c3bc5e452ac91559669087";
      hash = "sha256-wi9L4RcnJWUzTkC4u8vSTacrMxg4ftm/K7pkuwLEQ3U=";
    };
  };
  "friendly-snippets" = {
    version = "6cd7280";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "6cd7280adead7f586db6fccbd15d2cac7e2188b9";
      hash = "sha256-FzApcTbWfFkBD9WsYMhaCyn6ky8UmpUC2io/co/eByM=";
    };
  };
  "gitsigns.nvim" = {
    version = "v2.1.0";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "v2.1.0";
      hash = "sha256-ETVmrlUXmCiekjd68mY8657wg9CdQk/rPRv5ABO9pxk=";
    };
  };
  "guess-indent.nvim" = {
    version = "84a4987";
    src = fetchFromGitHub {
      owner = "NMAC427";
      repo = "guess-indent.nvim";
      rev = "84a4987ff36798c2fc1169cbaff67960aed9776f";
      hash = "sha256-M/FkwCXXhojVFEcCuHo/GkuCCSX9GlVYHBUECSZxBjs=";
    };
  };
  "heirline.nvim" = {
    version = "v1.0.8";
    src = fetchFromGitHub {
      owner = "rebelot";
      repo = "heirline.nvim";
      rev = "v1.0.8";
      hash = "sha256-kHoaeULWI+NrLp0am0DSKRKeA1vZIg4pt5NxZuFUDvY=";
    };
  };
  "lazydev.nvim" = {
    version = "ff2cbcb";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "ff2cbcba459b637ec3fd165a2be59b7bbaeedf0d";
      hash = "sha256-Tsg1wNdySi6nK00sq1qDBRkRRlpdMCXVToDJ1SiqnPQ=";
    };
  };
  "mason-lspconfig.nvim" = {
    version = "25f609e";
    src = fetchFromGitHub {
      owner = "mason-org";
      repo = "mason-lspconfig.nvim";
      rev = "25f609e7fca78af7cede4f9fa3af8a94b1c4950b";
      hash = "sha256-VjnN8NMXDjayF3whr2Oa5fQJmW18+798q9T4jFxAG3U=";
    };
  };
  "mason-null-ls.nvim" = {
    version = "v2.6.0";
    src = fetchFromGitHub {
      owner = "jay-babu";
      repo = "mason-null-ls.nvim";
      rev = "v2.6.0";
      hash = "sha256-EyOcThSnsT7YltYl/N0u24BjFA5fkYWpQouQwz61P8k=";
    };
  };
  "mason-nvim-dap.nvim" = {
    version = "v2.5.2";
    src = fetchFromGitHub {
      owner = "jay-babu";
      repo = "mason-nvim-dap.nvim";
      rev = "v2.5.2";
      hash = "sha256-y1heAB1HCntH4m5wITMejVQW0XxfmxjE/ZBZHrMNges=";
    };
  };
  "mason-tool-installer.nvim" = {
    version = "443f1ef";
    src = fetchFromGitHub {
      owner = "WhoIsSethDaniel";
      repo = "mason-tool-installer.nvim";
      rev = "443f1ef8b5e6bf47045cb2217b6f748a223cf7dc";
      hash = "sha256-OZGq2TKZx1+GSzrQAdk2fAUv3052NMfTkm5QdO+EXXk=";
    };
  };
  "mason.nvim" = {
    version = "v2.2.1";
    src = fetchFromGitHub {
      owner = "mason-org";
      repo = "mason.nvim";
      rev = "v2.2.1";
      hash = "sha256-IeBKl+JOwRQqpdKQqO1v91/7qtUuro83+EXiSgoLgi4=";
    };
  };
  "mini.icons" = {
    version = "v0.17.0";
    src = fetchFromGitHub {
      owner = "nvim-mini";
      repo = "mini.icons";
      rev = "v0.17.0";
      hash = "sha256-yns7HZFklgkiXoQJheDRAAtmoKTW9g+hpT/gf5DzwAw=";
    };
  };
  "neo-tree.nvim" = {
    version = "3.40.0";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "3.40.0";
      hash = "sha256-/TNl/IX81qr7Mcoy0dhF3bcsewXEnPSy2n+dm31eyyw=";
    };
  };
  "none-ls.nvim" = {
    version = "7f9301e";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "7f9301e416533b5d74e2fb3b1ce5059eeaed748b";
      hash = "sha256-5s1ZpC+RyCiRwIbWlWALKrWvozpvXjdlavVfF1cx7hQ=";
    };
  };
  "nui.nvim" = {
    version = "0.4.0";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "0.4.0";
      hash = "sha256-SJc9nfV6cnBKYwRWsv0iHy+RbET8frNV85reICf+pt8=";
    };
  };
  "nvim-autopairs" = {
    version = "59bce2e";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "59bce2eef357189c3305e25bc6dd2d138c1683f5";
      hash = "sha256-0IqXpxKCzqVz6i9QajPYJ0FdfReHQBhehrvN89/8n6U=";
    };
  };
  "nvim-dap" = {
    version = "45a69eb";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "45a69eba683a2c448dd9ecfc4de89511f0646b5f";
      hash = "sha256-9NF0+QoHOEAg6pd+oRBxr3ExWLqbvRrIMoMSZvNdqX4=";
    };
  };
  "nvim-dap-ui" = {
    version = "1a66cab";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "1a66cabaa4a4da0be107d5eda6d57242f0fe7e49";
      hash = "sha256-J/gUD4X//JtC2HB3HBeONivCQdMnXDnZJWd6jFF9+nk=";
    };
  };
  "nvim-highlight-colors" = {
    version = "e2cb220";
    src = fetchFromGitHub {
      owner = "brenoprata10";
      repo = "nvim-highlight-colors";
      rev = "e2cb22089cc2358b2b995c09578224f142de6039";
      hash = "sha256-LrY61knLKAn36+RnMddAzxf/wYtdnLxnnQhtHB3mQwc=";
    };
  };
  "nvim-lspconfig" = {
    version = "v2.8.0";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "v2.8.0";
      hash = "sha256-boQBpuqeGLQV0Vnx+9zecxPEHRVnJMAWVmSld6msS7E=";
    };
  };
  "nvim-nio" = {
    version = "v1.10.1";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "v1.10.1";
      hash = "sha256-eDbzJAGdUBhTwuD0Nt9FihZj1MmVdQfn/GKIybuu5a8=";
    };
  };
  "nvim-treesitter" = {
    version = "4916d65";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "4916d6592ede8c07973490d9322f187e07dfefac";
      hash = "sha256-PQR6tFt4lCrAZNQG7BLMD1IiCKja9wDS1S4laGJf/HE=";
    };
  };
  "nvim-treesitter-textobjects" = {
    version = "851e865";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "851e865342e5a4cb1ae23d31caf6e991e1c99f1e";
      hash = "sha256-fOpRElIwvsFWm4AwETx7fpC3RtdH2BpCfX4YHVitqw0=";
    };
  };
  "nvim-ts-autotag" = {
    version = "8e1c0a3";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "8e1c0a389f20bf7f5b0dd0e00306c1247bda2595";
      hash = "sha256-a6xnl1IyKLMEeaw3OIuwdNx10HFPYxExVuGWAhaim+M=";
    };
  };
  "nvim-window-picker" = {
    version = "v2.4.0";
    src = fetchFromGitHub {
      owner = "s1n7ax";
      repo = "nvim-window-picker";
      rev = "v2.4.0";
      hash = "sha256-ZavIPpQXLSRpJXJVJZp3N6QWHoTKRvVrFAw7jekNmX4=";
    };
  };
  "plenary.nvim" = {
    version = "b9fd522";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "b9fd5226c2f76c951fc8ed5923d85e4de065e509";
      hash = "sha256-9Un7ekhBxcnmFE1xjCCFTZ7eqIbmXvQexpnhduAg4M0=";
    };
  };
  "resession.nvim" = {
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "resession.nvim";
      rev = "v1.2.1";
      hash = "sha256-GXKDuKDMcfl1SHTTdUFdWuWbtq6TDtk0GsyI3fAc1vE=";
    };
  };
  "smart-splits.nvim" = {
    version = "0bd0216";
    src = fetchFromGitHub {
      owner = "mrjones2014";
      repo = "smart-splits.nvim";
      rev = "0bd02161ee5c5378bf4133fcedf53d1fc4179e1d";
      hash = "sha256-Jg4/opFVFMfDFjcoBTvuOyWdONAjBTc25jsP4ksopL8=";
    };
  };
  "snacks.nvim" = {
    version = "v2.31.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "v2.31.0";
      hash = "sha256-NSoZQajyYFGIUCLD1m6FRPgKRsyJSM0IWygg1ofZZBs=";
    };
  };
  "todo-comments.nvim" = {
    version = "v1.5.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "v1.5.0";
      hash = "sha256-VGeIRfwQsHgSO89Pmn6yIP9na1F6mmYZx0HDLe9IKCQ=";
    };
  };
  "toggleterm.nvim" = {
    version = "v2.13.1";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "v2.13.1";
      hash = "sha256-Xc3TZUA6glsuchignUSk4gLZs1IBvI+YnWeP1r+snbQ=";
    };
  };
  "which-key.nvim" = {
    version = "v3.17.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "v3.17.0";
      hash = "sha256-kYpiw2Syu54B/nNVqTZeUHJIPNzAv3JpFaMWR9Ai3p4=";
    };
  };
}
