# Generated by ./update.sh - do not update manually!
# Last updated: 2026-08-29
{ fetchFromGitHub }:
{
  "LuaSnip" = {
    version = "v2.5.0";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "v2.5.0";
      hash = "sha256-diZO1on0rlSp6XuNGN2lNa85rhkNe1QQOejJD+LKkZk=";
    };
  };
  "aerial.nvim" = {
    version = "v3.1.0";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "aerial.nvim";
      rev = "v3.1.0";
      hash = "sha256-ugzNA/+Z2ReIy/8ks9wHEtmpTwpr8qqVR0xemw+GrUc=";
    };
  };
  "astrocore" = {
    version = "v3.1.0";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "astrocore";
      rev = "v3.1.0";
      hash = "sha256-ALLA4JVCfn1VS24uZEVkSN3wTW3df3RlmSQLbpn+pPk=";
    };
  };
  "astrolsp" = {
    version = "v4.0.1";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "astrolsp";
      rev = "v4.0.1";
      hash = "sha256-blKHK0dxMS1cW+8bk8wyWGmigLWkp2sl7wzxA5AW3tg=";
    };
  };
  "astrotheme" = {
    version = "v4.13.0";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "astrotheme";
      rev = "v4.13.0";
      hash = "sha256-1VppLnCIrkos3x5NYq6PONbe7pbAfNUWGbZvHtYd8cM=";
    };
  };
  "astroui" = {
    version = "v4.0.2";
    src = fetchFromGitHub {
      owner = "AstroNvim";
      repo = "astroui";
      rev = "v4.0.2";
      hash = "sha256-WPCl2crE4r9fGHRHCKZQcmQnvogSRwE4+K9jFQrUTD0=";
    };
  };
  "better-escape.nvim" = {
    version = "v2.3.3";
    src = fetchFromGitHub {
      owner = "max397574";
      repo = "better-escape.nvim";
      rev = "v2.3.3";
      hash = "sha256-47j0FKQ74HXYHWuKgAlDioGFdYk/XxGU9Qswdd4Rnxw=";
    };
  };
  "blink.cmp" = {
    version = "v1.10.2";
    src = fetchFromGitHub {
      owner = "saghen";
      repo = "blink.cmp";
      rev = "v1.10.2";
      hash = "sha256-C1FpyGw0f35NdHvDUGPXxmKdOgw3SpIteK1gAjVy6Ns=";
    };
  };
  "blink.compat" = {
    version = "v2.5.0";
    src = fetchFromGitHub {
      owner = "saghen";
      repo = "blink.compat";
      rev = "v2.5.0";
      hash = "sha256-GluPgQ8EPH9XXsyLnw//sh1lcDEdcu3VbYQG4ns5JAE=";
    };
  };
  "cmp-dap" = {
    version = "ea92773";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "cmp-dap";
      rev = "ea92773e84c0ad3288c3bc5e452ac91559669087";
      hash = "sha256-wi9L4RcnJWUzTkC4u8vSTacrMxg4ftm/K7pkuwLEQ3U=";
    };
  };
  "friendly-snippets" = {
    version = "6cd7280";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "6cd7280adead7f586db6fccbd15d2cac7e2188b9";
      hash = "sha256-FzApcTbWfFkBD9WsYMhaCyn6ky8UmpUC2io/co/eByM=";
    };
  };
  "gitsigns.nvim" = {
    version = "v2.1.0";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "v2.1.0";
      hash = "sha256-ETVmrlUXmCiekjd68mY8657wg9CdQk/rPRv5ABO9pxk=";
    };
  };
  "guess-indent.nvim" = {
    version = "84a4987";
    src = fetchFromGitHub {
      owner = "NMAC427";
      repo = "guess-indent.nvim";
      rev = "84a4987ff36798c2fc1169cbaff67960aed9776f";
      hash = "sha256-M/FkwCXXhojVFEcCuHo/GkuCCSX9GlVYHBUECSZxBjs=";
    };
  };
  "heirline.nvim" = {
    version = "v1.0.8";
    src = fetchFromGitHub {
      owner = "rebelot";
      repo = "heirline.nvim";
      rev = "v1.0.8";
      hash = "sha256-kHoaeULWI+NrLp0am0DSKRKeA1vZIg4pt5NxZuFUDvY=";
    };
  };
  "lazydev.nvim" = {
    version = "ff2cbcb";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazydev.nvim";
      rev = "ff2cbcba459b637ec3fd165a2be59b7bbaeedf0d";
      hash = "sha256-Tsg1wNdySi6nK00sq1qDBRkRRlpdMCXVToDJ1SiqnPQ=";
    };
  };
  "mason-lspconfig.nvim" = {
    version = "7adc933";
    src = fetchFromGitHub {
      owner = "mason-org";
      repo = "mason-lspconfig.nvim";
      rev = "7adc933dabcc7c86ae6b07aff7ee68eac398491f";
      hash = "sha256-m71BZepmDdLmd0qCHXIdGiZVZke9obO4qFt7OR8p/do=";
    };
  };
  "mason-null-ls.nvim" = {
    version = "v2.6.0";
    src = fetchFromGitHub {
      owner = "jay-babu";
      repo = "mason-null-ls.nvim";
      rev = "v2.6.0";
      hash = "sha256-EyOcThSnsT7YltYl/N0u24BjFA5fkYWpQouQwz61P8k=";
    };
  };
  "mason-nvim-dap.nvim" = {
    version = "v2.5.2";
    src = fetchFromGitHub {
      owner = "jay-babu";
      repo = "mason-nvim-dap.nvim";
      rev = "v2.5.2";
      hash = "sha256-y1heAB1HCntH4m5wITMejVQW0XxfmxjE/ZBZHrMNges=";
    };
  };
  "mason-tool-installer.nvim" = {
    version = "443f1ef";
    src = fetchFromGitHub {
      owner = "WhoIsSethDaniel";
      repo = "mason-tool-installer.nvim";
      rev = "443f1ef8b5e6bf47045cb2217b6f748a223cf7dc";
      hash = "sha256-OZGq2TKZx1+GSzrQAdk2fAUv3052NMfTkm5QdO+EXXk=";
    };
  };
  "mason.nvim" = {
    version = "v2.3.1";
    src = fetchFromGitHub {
      owner = "mason-org";
      repo = "mason.nvim";
      rev = "v2.3.1";
      hash = "sha256-zx45l5yZeWgnkzaQeY+V3GK84arritj7jfpJ64Go9rg=";
    };
  };
  "mini.icons" = {
    version = "v0.17.0";
    src = fetchFromGitHub {
      owner = "nvim-mini";
      repo = "mini.icons";
      rev = "v0.17.0";
      hash = "sha256-yns7HZFklgkiXoQJheDRAAtmoKTW9g+hpT/gf5DzwAw=";
    };
  };
  "neo-tree.nvim" = {
    version = "3.41.0";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "3.41.0";
      hash = "sha256-OVYt5QMWHRs/ivFcblHcgbqNkg+xzohG+IifPJBfY3o=";
    };
  };
  "none-ls.nvim" = {
    version = "01f8e62";
    src = fetchFromGitHub {
      owner = "nvimtools";
      repo = "none-ls.nvim";
      rev = "01f8e62ea11603e59ad9ff7afcfa94fd183f76d6";
      hash = "sha256-Amz3UFxET/+poFUm+ldyPEdl9u9/DDMarvgF+AleC/U=";
    };
  };
  "nui.nvim" = {
    version = "0.4.0";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "0.4.0";
      hash = "sha256-SJc9nfV6cnBKYwRWsv0iHy+RbET8frNV85reICf+pt8=";
    };
  };
  "nvim-autopairs" = {
    version = "7b9923a";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "7b9923abad60b903ece7c52940e1321d39eccc79";
      hash = "sha256-klOJgBPw8oGDnF9wKIpGDzuBY+tH1acRyvZSPR4wrjw=";
    };
  };
  "nvim-dap" = {
    version = "9e848e0";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "9e848e09a697ee95302a3ef2dd43fd6eb709e570";
      hash = "sha256-IHm3CwO7qUTtOZqhljDjSzz4WbaAJ4kPY384MyZZ9ac=";
    };
  };
  "nvim-dap-ui" = {
    version = "cc9dd33";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "cc9dd33aade7f20bae414d0cba163bc60d4d4b43";
      hash = "sha256-za3/6W1J6aMvNZQq8ANCq+TGHKHJtSxR/C5t3/oL3DI=";
    };
  };
  "nvim-highlight-colors" = {
    version = "e4c7af0";
    src = fetchFromGitHub {
      owner = "brenoprata10";
      repo = "nvim-highlight-colors";
      rev = "e4c7af0211866162d999ce0bdd6a029302e19139";
      hash = "sha256-4tkehMJpMs/CrQrCFqy+4G9uQei9mAoQlwvxuYtu7z8=";
    };
  };
  "nvim-lspconfig" = {
    version = "v2.11.0";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "v2.11.0";
      hash = "sha256-d1vDEfiNSo9ccSPqTHEFqXVFCPhp/0ZozTzcyLiJrGg=";
    };
  };
  "nvim-nio" = {
    version = "v1.10.1";
    src = fetchFromGitHub {
      owner = "nvim-neotest";
      repo = "nvim-nio";
      rev = "v1.10.1";
      hash = "sha256-eDbzJAGdUBhTwuD0Nt9FihZj1MmVdQfn/GKIybuu5a8=";
    };
  };
  "nvim-treesitter" = {
    version = "61df849";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "61df84986b4b4ec469ee745a182e433d49f8c27e";
      hash = "sha256-h0O7KX8rIAhOW5MxQPvw9MeTNsjBxP2JuS/9sgcfzrw=";
    };
  };
  "nvim-treesitter-textobjects" = {
    version = "898ee30";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "898ee307df58f854d11cd7edd06472574d48014e";
      hash = "sha256-naZ+p5RrC+uUyFRaksmozDfNgJRifff+9TDWx79DCPk=";
    };
  };
  "nvim-ts-autotag" = {
    version = "88c1453";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "88c1453db4ba7dd24131086fe51fdf74e587d275";
      hash = "sha256-bvBf9wEDxdwlMGN29v4dEPexZGuxZZr7s+6xAOrDNKI=";
    };
  };
  "nvim-window-picker" = {
    version = "v2.4.0";
    src = fetchFromGitHub {
      owner = "s1n7ax";
      repo = "nvim-window-picker";
      rev = "v2.4.0";
      hash = "sha256-ZavIPpQXLSRpJXJVJZp3N6QWHoTKRvVrFAw7jekNmX4=";
    };
  };
  "plenary.nvim" = {
    version = "74b06c6";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "74b06c6c75e4eeb3108ec01852001636d85a932b";
      hash = "sha256-nkfETDkPiE+Kd2BWYZijgUp9bP8RgFwRmvqJz2BMuq4=";
    };
  };
  "resession.nvim" = {
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "resession.nvim";
      rev = "v1.2.1";
      hash = "sha256-GXKDuKDMcfl1SHTTdUFdWuWbtq6TDtk0GsyI3fAc1vE=";
    };
  };
  "smart-splits.nvim" = {
    version = "32f6788";
    src = fetchFromGitHub {
      owner = "mrjones2014";
      repo = "smart-splits.nvim";
      rev = "32f67888ac71942442fdab3819864a10449dfc41";
      hash = "sha256-1DRSj+xhXKjInkHFvM+Dbe63yPVv2hlTuw3SqeiFdv4=";
    };
  };
  "snacks.nvim" = {
    version = "v2.31.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "v2.31.0";
      hash = "sha256-NSoZQajyYFGIUCLD1m6FRPgKRsyJSM0IWygg1ofZZBs=";
    };
  };
  "todo-comments.nvim" = {
    version = "v1.5.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "v1.5.0";
      hash = "sha256-VGeIRfwQsHgSO89Pmn6yIP9na1F6mmYZx0HDLe9IKCQ=";
    };
  };
  "toggleterm.nvim" = {
    version = "v2.13.1";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "v2.13.1";
      hash = "sha256-Xc3TZUA6glsuchignUSk4gLZs1IBvI+YnWeP1r+snbQ=";
    };
  };
  "which-key.nvim" = {
    version = "v3.17.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "v3.17.0";
      hash = "sha256-kYpiw2Syu54B/nNVqTZeUHJIPNzAv3JpFaMWR9Ai3p4=";
    };
  };
}
