#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure -p cacert coreutils gh git jq luajit luajitPackages.cjson nix nodePackages.semver
# shellcheck shell=bash

set -euo pipefail

cd "$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")"

function info {
  echo "[INFO] $*" >&2
}

function warn {
  echo "[WARN] $*" >&2
}

function error {
  echo "[ERROR] $*" >&2
}

function parse_snapshot {
  luajit - "$1" <<EOF
local cjson = require("cjson")
local snapshot = dofile(arg[1])
for _, entry in ipairs(snapshot) do
  print(cjson.encode({
    name = entry[1],
    commit = entry.commit,
    version = entry.version,
  }))
end
EOF
}

function resolve_semver_tag {
  local owner="$1" repo="$2" constraint="$3"

  local -a tag_names
  mapfile -t tag_names < <(gh api "repos/${owner}/${repo}/tags" --paginate --jq '.[].name')

  if [[ ${#tag_names[@]} -eq 0 ]]; then
    error "no tags found for ${owner}/${repo}"
    return 1
  fi

  local resolved
  resolved="$(semver -r "${constraint}" "${tag_names[@]}" | tail -1)"

  if [[ -z "${resolved}" ]]; then
    error "no tag matching '${constraint}' for ${owner}/${repo}"
    return 1
  fi

  local tag
  for tag in "${tag_names[@]}"; do
    if [[ "${tag}" == "${resolved}" || "${tag}" == "v${resolved}" ]]; then
      echo "${tag}"
      return
    fi
  done

  error "resolved ${resolved} but could not find matching tag for ${owner}/${repo}"
  return 1
}

function prefetch_plugin {
  local owner="$1" repo="$2" rev="$3"
  local url="https://github.com/${owner}/${repo}/archive/${rev}.tar.gz"
  local base32_hash sri_hash

  base32_hash="$(nix-prefetch-url --unpack "${url}" 2>/dev/null)"
  sri_hash="$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "${base32_hash}")"
  echo "${sri_hash}"
}

function process_snapshot_entry {
  local json="$1"
  local name owner repo commit constraint rev version hash source detail

  name="$(jq -r '.name' <<<"${json}")"
  owner="${name%%/*}"
  repo="${name##*/}"

  [[ "${name}" == "folke/lazy.nvim" ]] && return 0

  commit="$(jq -r '.commit // empty' <<<"${json}")"
  constraint="$(jq -r '.version // empty' <<<"${json}")"

  if [[ -n "${commit}" ]]; then
    rev="${commit}"
    version="${commit:0:7}"
    source="commit"
    detail="-"
  elif [[ -n "${constraint}" ]]; then
    rev="$(resolve_semver_tag "${owner}" "${repo}" "${constraint}")"
    version="${rev}"
    source="semver"
    detail="${constraint}"
  else
    warn "skipping ${name} (no commit or version)"
    return 0
  fi

  hash="$(prefetch_plugin "${owner}" "${repo}" "${rev}")"

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "${owner}" "${repo}" "${rev}" "${version}" "${hash}" "${source}" "${detail}"
}

export -f resolve_semver_tag
export -f prefetch_plugin
export -f process_snapshot_entry

function main {
  local ASTRONVIM_SRC
  ASTRONVIM_SRC="$(nix --extra-experimental-features 'nix-command flakes' eval --raw ../../..#astronvim-src)"
  local SNAPSHOT="${ASTRONVIM_SRC}/lua/astronvim/lazy_snapshot.lua"

  if [[ ! -f "${SNAPSHOT}" ]]; then
    error "lazy_snapshot.lua not found at ${SNAPSHOT}"
    exit 1
  fi

  info "Reading snapshot from ${SNAPSHOT}"

  local TEMPDIR
  TEMPDIR="$(mktemp -d)"
  trap 'rm -rf "${TEMPDIR}"' EXIT INT TERM

  local RAW_RESULTS="${TEMPDIR}/plugins.raw.tsv"
  local SORTED_RESULTS="${TEMPDIR}/plugins.sorted.tsv"

  local JOBS="${JOBS:-$(nproc)}"
  info "Resolving and prefetching plugins with ${JOBS} jobs"

  # shellcheck disable=SC2016 # False positive
  parse_snapshot "${SNAPSHOT}" \
    | while IFS= read -r json; do
      printf '%s\0' "${json}"
    done \
    | xargs -0 -n1 -P "${JOBS}" bash -euo pipefail -c 'process_snapshot_entry "$1"' _ \
      >"${RAW_RESULTS}"

  sort -t $'\t' -k2,2 "${RAW_RESULTS}" >"${SORTED_RESULTS}"

  local OUTPUT="sources.nix"

  {
    cat - <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{ fetchFromGitHub }:
{
EOF

    while IFS=$'\t' read -r p_owner p_repo p_rev p_version p_hash p_source p_detail; do
      [[ -z "${p_repo}" ]] && continue
      if [[ "${p_source}" == "commit" ]]; then
        info "  ${p_owner}/${p_repo} @ ${p_version} (commit-pinned) => ${p_hash}"
      else
        info "  ${p_owner}/${p_repo} ${p_detail} => ${p_rev} => ${p_hash}"
      fi
      cat <<EOF
  "${p_repo}" = {
    version = "${p_version}";
    src = fetchFromGitHub {
      owner = "${p_owner}";
      repo = "${p_repo}";
      rev = "${p_rev}";
      hash = "${p_hash}";
    };
  };
EOF
    done <"${SORTED_RESULTS}"

    echo "}"
  } >"${OUTPUT}"

  info "Generated ${OUTPUT}"
}

main "${@}"
