#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure -p cacert coreutils gh git jq luajit luajitPackages.cjson nix nodePackages.semver
# shellcheck shell=bash

set -euo pipefail

cd "$(readlink -e "$(dirname "${BASH_SOURCE[0]}")")"

ASTRONVIM_SRC="$(nix --extra-experimental-features 'nix-command flakes' eval --raw ../..#astronvim-src)"
SNAPSHOT="${ASTRONVIM_SRC}/lua/astronvim/lazy_snapshot.lua"

if [[ ! -f "${SNAPSHOT}" ]]; then
  echo "error: lazy_snapshot.lua not found at ${SNAPSHOT}" >&2
  exit 1
fi

echo "Reading snapshot from ${SNAPSHOT}" >&2

parse_snapshot() {
  luajit - "$1" <<'LUA'
local cjson = require("cjson")
local snapshot = dofile(arg[1])
for _, entry in ipairs(snapshot) do
  print(cjson.encode({
    name = entry[1],
    commit = entry.commit,
    version = entry.version,
  }))
end
LUA
}

resolve_semver_tag() {
  local owner="$1" repo="$2" constraint="$3"

  local -a tag_names
  mapfile -t tag_names < <(gh api "repos/${owner}/${repo}/tags" --paginate --jq '.[].name')

  if [[ ${#tag_names[@]} -eq 0 ]]; then
    echo "error: no tags found for ${owner}/${repo}" >&2
    return 1
  fi

  local resolved
  resolved="$(semver -r "${constraint}" "${tag_names[@]}" | tail -1)"

  if [[ -z "${resolved}" ]]; then
    echo "error: no tag matching '${constraint}' for ${owner}/${repo}" >&2
    return 1
  fi

  local tag
  for tag in "${tag_names[@]}"; do
    if [[ "${tag}" == "${resolved}" || "${tag}" == "v${resolved}" ]]; then
      echo "${tag}"
      return
    fi
  done

  echo "error: resolved ${resolved} but could not find matching tag for ${owner}/${repo}" >&2
  return 1
}

prefetch_plugin() {
  local owner="$1" repo="$2" rev="$3"
  local url="https://github.com/${owner}/${repo}/archive/${rev}.tar.gz"
  local base32_hash sri_hash

  base32_hash="$(nix-prefetch-url --unpack "${url}" 2>/dev/null)"
  sri_hash="$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "${base32_hash}")"
  echo "${sri_hash}"
}

declare -A plugins

while IFS= read -r json; do
  name="$(jq -r '.name' <<<"${json}")"
  owner="${name%%/*}"
  repo="${name##*/}"

  [[ "${name}" == "folke/lazy.nvim" ]] && continue

  commit="$(jq -r '.commit // empty' <<<"${json}")"
  constraint="$(jq -r '.version // empty' <<<"${json}")"

  if [[ -n "${commit}" ]]; then
    rev="${commit}"
    version="${commit:0:7}"
    echo "  ${name} @ ${version} (commit-pinned)" >&2
  elif [[ -n "${constraint}" ]]; then
    echo -n "  ${name} ${constraint} -> " >&2
    rev="$(resolve_semver_tag "${owner}" "${repo}" "${constraint}")"
    version="${rev}"
    echo "${rev}" >&2
  else
    echo "warning: skipping ${name} (no commit or version)" >&2
    continue
  fi

  echo -n "    prefetching... " >&2
  hash="$(prefetch_plugin "${owner}" "${repo}" "${rev}")"
  echo "${hash}" >&2

  plugins["${repo}"]="${owner} ${repo} ${rev} ${version} ${hash}"
done < <(parse_snapshot "${SNAPSHOT}")

OUTPUT="sources.nix"

{
  cat - <<HEADER
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{ fetchFromGitHub }:
{
HEADER

  for name in $(echo "${!plugins[@]}" | tr ' ' '\n' | sort); do
    read -r p_owner p_repo p_rev p_version p_hash <<<"${plugins[${name}]}"
    cat <<ENTRY
  "${name}" = {
    version = "${p_version}";
    src = fetchFromGitHub {
      owner = "${p_owner}";
      repo = "${p_repo}";
      rev = "${p_rev}";
      hash = "${p_hash}";
    };
  };
ENTRY
  done

  echo "}"
} >"${OUTPUT}"

echo "Generated ${OUTPUT}" >&2
